module.exports = {
    Client: require('./src/Client.js'),
    Bot: require('./src/bot.js'),
    StackExchangeClient: require('./src/platform/StackExchange/StackExchangeClient.js'),
    DiscordClient: require('./src/platform/Discord/DiscordClient.js'),
    ChatEvent: require('./src/events/ChatEvent.js'),
    Message: require('./src/events/Message.js'),
    pluginStore: {
        main: {
            adoc: require('./src/plugins/adoc'),
            afk: require('./src/plugins/afk'),
            applesupport: require('./src/plugins/applesupport'),
            ban: require('./src/plugins/ban'),
            betterecho: require('./src/plugins/betterecho'),
            calc: require('./src/plugins/calc'),
            eval: require('./src/plugins/eval.js'),
            funfact: require('./src/plugins/funfact'),
            goodbye: require('./src/plugins/goodbye'),
            java: require('./src/plugins/java'),
            joke: require('./src/plugins/joke'),
            kill: require('./src/plugins/kill'),
            learn: require('./src/plugins/learn'),
            mdn: require('./src/plugins/mdn'),
            random: require('./src/plugins/random'),
            rules: require('./src/plugins/rules'),
            stat: require('./src/plugins/stat'),
            timer: require('./src/plugins/timer'),
            unformatted_code: require('./src/plugins/unformatted-code'),
            wiki: require('./src/plugins/wiki'),
            youmessedup: require('./src/plugins/youmessedup'),

        },
        default: {
            help: require('./src/plugins/default/help'),
            info: require('./src/plugins/default/info'),
            life: require('./src/plugins/default/life'),
            selfDestruct: require('./src/plugins/default/selfDestruct'),
            status: require('./src/plugins/default/status'),
            welcome: require('./src/plugins/default/welcome'),
        },
    },
};
